apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sre-deployment
  labels:
    app: sre-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sre-demo
  template:
    metadata:
      labels:
        app: sre-demo
    spec:
      containers:
        - image: ajduet/sre-demo:%TAG%
          imagePullPolicy: Always
          name: sre-demo
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /hw
              port: 8080
          readinessProbe:
            httpGet:
              path: /hw
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: sre-demo
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
